### ISSUE TITLE
error while processing erosion

### ISSUE THREAD

**Issue by clauvasq** [CellProfiler/tutorials#11]
Hi,
I'm stepping through your 3d_monolayer tutorial (with the provided sample dataset). I've been successful following along until just after the "ConvertObjectsToImage" module.  When I run the "Erosion" module, I get an error that sttes,  "footprint array has incorrect shape." Currently I've tried the following shape, sizes combos:
ball, 3 (as instructed in the tutorial)
disk, 5 (what the current pipeline on github shows [3d_monolayer_final.cppipe])
disk, 3
square, 3
All pop up the same footprint error message. Is there a way for me to access the matrix that CP is trying to use as a structuring element? Or is there something else I can test?

**Comment by bethac07** [comment]
Hmmm, it works fine in my hands for both ball 3 and disk 5 (though thank you for pointing out the discrepancy, we'll make sure to fix that!).  What CP version/OS/etc?

**Comment by clauvasq** [comment]
CP 3.0.0, OSX 10.13. Let me know if there’s any other info I can provide.

On Oct 19, 2017, at 6:15 PM, bethac07 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm, it works fine in my hands for both ball 3 and disk 5 (though thank you for pointing out the discrepancy, we'll make sure to fix that!). What CP version/OS/etc?
