### ISSUE TITLE
pipeline error when import pipeline

### ISSUE THREAD

**Issue by yuewensong** [CellProfiler/tutorials#18]
win7_x64
cellprofiler version:  2.1.1 (newest version ok for my pc)
(newer version shows "can't find the JVM, Failed to execute scripts CellProfiler". I have googled some suggestion, still failed)

When I tried to import [objects_from_gimp_outlines.cppipe](https://github.com/CellProfiler/tutorials/blob/master/Annotation/objects_from_gimp_outlines.cppipe) (locally), it shows the following messages:
error while loading none:Unkonwn mat file type, version 100, 110 
Do you want to stop processing?_

I have checked related [lin1](https://github.com/CellProfiler/CellProfiler/issues/1349) , [lin2](https://github.com/CellProfiler/CellProfiler/issues/1318). Still I cannot figure the problem out.

I am new to cellprofiler. can anyone help me?

**Comment by bethac07** [comment]
Hi,

That pipeline will only work on CellProfiler 3.1 and above.  CellProfiler pipelines are forwards compatible, but not backwards compatible.  Sorry!

**Comment by yuewensong** [comment]
> Hi,
> 
> That pipeline will only work on CellProfiler 3.1 and above. CellProfiler pipelines are forwards compatible, but not backwards compatible. Sorry!

Thanks, beth!

I reinstall cellprofiler3.15 again, and finally I did it! Incase anyone has the same problem, I did the following things to finish the installation.
my_pc_info: win7_x64
1. install [jdk-11_windows-x64_bin](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html) on drive C....
2. install [jdk-8u181-windows-x64](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) on drive C.....
3. install cellprofiler 2.1.1 on drive D.... (I guess it can be installed on C....)
4. install cellprofiler 3.0.0 on dreve C.....
5. install cellprofiler 3.1.5 in the same path with cellproflier 3.0.0

for potential issues like
1. 'Fatal error: Failed to execute scripts CellProfiler': you may solve this by installing newer version on the basis of older version
2. 'ValueError: path is on drive C:, start on drive d': you may solve this by installing java and cellprofiler in the same drive.

hope it helps.
