### ISSUE TITLE
Error message during Erosion

### ISSUE THREAD

**Issue by mquintero1** [CellProfiler/tutorials#23]
I am trying to count number of nuclei within GFP+ cytoplasm and get the volume of that GFP+ area. I will attach an image example below. My first issue is I keep on getting an error message that reads "error while processing erosion: footprint array has incorrect shape and gives me the option to continue processing. What does this mean and how can I fix it?

Also is there a way to get an excel type of file or data table that includes the number of nuclei and the volume of the GFP+?

Thank you for the help, I really appreciate it. I'm very new at this and it has been quite a difficult process for me to learn any tips would be great.

**Comment by bethac07** [comment]
Hi,

This really isn't the right place for this, can you post your question (and sample pipeline and images) over at image.sc ? We'll be better able to help you there.  Thanks!
