### ISSUE TITLE
Speed up build by excluding most directories

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/tutorials#40]
Jekyll allows you to add [excluded folders (and to allow included individual files in those folders)](https://jekyllrb.com/docs/configuration/options/). Right now, build takes ~20+ minutes, and most of it is analyzing and tarballing the whole repo, which we don't need most of for the little webpage. We should be able to take that way down.

**Comment by rsenft1** [comment]
Yes this dramatically improved build speed! 
<img width="140" alt="image" src="https://user-images.githubusercontent.com/28116530/185947740-7f00b079-6bdf-4a0b-a8f1-6e4e385aae60.png">
I experimented with just blanket excluding all with wildcard then including specific folders, but it complained no matter what I tried for selecting all folders (**/, */, **). So right now I'm explicitly excluding each folder.

**Comment by bethac07** [comment]
(I looked at the commits, I'm not sure if blanket-excluding all things but then specifying that you definitely weren't excluding the config and the README would have fixed it. But since we don't add new tutorials super regularly, it seems like this is a perfectly fine solution, we may just want to add a "edit the config" section to the "adding a new tutorial" documentation

**Comment by rsenft1** [comment]
Yes I tried excluding all folders, then the [last commit](https://github.com/CellProfiler/tutorials/commit/d1ea1a516f21adcaaad4f5391a5b1d599bcf71bb) excluded "everything" with ** but explicitly included the config and readme. The error was always about that line having an unknown character on that line in the _config.yml: `did not find expected alphabetic or numeric character while scanning an alias at line 21 column 3`. I'm unsure if excluding that way is allowed or if I just have the syntax wrong. [Here](https://idratherbewriting.com/documentation-theme-jekyll/mydoc_exluding_files.html) is what I was working from (that and how it works for .gitignore files), though I haven't found any documentation about how to exclude everything

**Comment by bethac07** [comment]
Ah, sorry, missed that one. Line 21 though was your exclude line though, so it seems like it was mad with your exclude rather than your include. 

<img width="183" alt="image" src="https://user-images.githubusercontent.com/6721515/185957632-e0302a79-30c9-41f3-a1ec-223da0f6692e.png">

**Comment by bethac07** [comment]
You might need to put that in quotes - see examples [here](https://github.com/jekyll/jekyll/issues/948#issuecomment-16269424)

**Comment by rsenft1** [comment]
Yes it's the exclude that I'm unsure of how to do, the include works fine. Thanks, I'll try out the quotes!
