### ISSUE TITLE
Input modules tutorial 3D example 2 still has corrupted files

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/tutorials#43]
We should remove them and replace with a link to this folder

https://drive.google.com/drive/folders/1fj7G0AWwMcpRlDivy4FHL2mqGLJhpRHn

**Comment by rsenft1** [comment]
Suggestion: Input Tutorials has so many files that we could replace the download link (which currently directs to the repo, which is not friendly for beginners) with a link to a google drive folder containing all the files. What do you think @bdiazroh ?

**Comment by bdiazroh** [comment]
Yes we can do that, I just updated the [folder](https://drive.google.com/drive/folders/1Hy7L8tIfXjxbbwR-_AOi1oYA_R4xZHHt?usp=share_link) that Beth linked to and it now contains everything as it is on the repo/blog/tutorial. I will have to change it ownership and permissions, What would be the appropriate folder to move it to?.
