### ISSUE TITLE
Incomplete translations

### ISSUE THREAD

**Issue by emiglietta** [CellProfiler/tutorials#90]
**I just noticed (a few people mentioned it during the workshop) that the Spanish version of the tutorial still had a few english chunks here and there.**

![image](https://github.com/CellProfiler/tutorials/assets/58238709/ac482516-cbbe-4889-a5ea-dc90546da6da)

**This does not happen in the Portuguese version.
I checked all my other translations and the same thing happens for Translocation and Advanced Segmentation too  (in these cases limited to the titles only) but not in 3D cell Monolayer.**

![image](https://github.com/CellProfiler/tutorials/assets/58238709/f6ca426f-0557-4669-840d-a474026c70e5)
![image](https://github.com/CellProfiler/tutorials/assets/58238709/f68c9944-17d9-41cb-a723-ff1326adfaa7)

**I checked Transifex and all the unstranslated chunks I see are fully translated and the there is no Transifex PR left to pull to Main in the repo.**

![image](https://github.com/CellProfiler/tutorials/assets/58238709/2b2cccab-0598-41a9-8006-e49a052c7aa4)

**The po files are OK too, the untranslated chunks are properly translated there so there must be an issue when building the html**

**Comment by emiglietta** [comment]
The only weird thing I get when i run sphinx-build -b html -D language=es -D root_doc=toc_es/index . ../build/html_es is:
WARNING: html_static_path entry '_static' does not exist

**Comment by bethac07** [comment]
Can you check if what's in Transifex is the absolute most up to date version, aka is it possible that the script that generates updated pot's from the md updates got run?

**Comment by emiglietta** [comment]
OK, as far as i could check (I checked some of the last commits where I changed that tutorial) yes, transifex is using the most up to date version of the pot.

**Comment by bethac07** [comment]
Resolved by #91 and #92 . A few translations (likely due to all the heroic copy-and-pasting efforts that needed to happen due to me not knowing what I was doing and set up right the first time) started with `- `, which apparently makes a silent barf happen where that translation doesn't get used. Fixed in tfx, new versions should be good to build now.
